---
- name: Generate Device Configuration
  connection: local
#  hosts: device_roles_access_switch, device_roles_wan_router
  hosts: device_roles_access,device_roles_distribution 
#  hosts: Test-Env-Access_sw02
  gather_facts: False

  roles:
    - role: generate_config
      tags: generate_config 
